# Generated by Django 3.0 on 2020-02-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
    ]
