# Generated by Django 3.0 on 2020-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('price', models.IntegerField()),
                ('type_of_food', models.IntegerField(choices=[(1, 'pizza'), (2, 'pasta')])),
            ],
        ),
    ]
