# Generated by Django 3.0 on 2020-01-25 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrescoBasilico', '0002_orderdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('appartment_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ref_code', models.CharField(default='', max_length=15)),
                ('payment', models.IntegerField(choices=[(1, 'cash'), (2, 'card')])),
                ('delivery_type', models.IntegerField(choices=[(1, 'pickup'), (2, 'delivery')])),
                ('special_instructions', models.TextField(blank=True, max_length=256)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FrescoBasilico.OrderDriver')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivered_to_address', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FrescoBasilico.Address')),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderedMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FrescoBasilico.Meals')),
                ('ordered_meals_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FrescoBasilico.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='FrescoBasilico.OrderedMeals'),
        ),
    ]
