# Generated by Django 3.0 on 2020-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrescoBasilico', '0003_auto_20200125_0928'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(to='User.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='orders',
            field=models.ManyToManyField(to='FrescoBasilico.Order'),
        ),
    ]
