# Generated by Django 3.0 on 2020-02-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrescoBasilico', '0007_auto_20200201_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('people', models.CharField(choices=[('1', 'one person'), ('2', 'two people'), ('3', 'three people'), ('4', 'four people'), ('5', 'five  people')], default='1', max_length=1)),
                ('time', models.TimeField()),
                ('date_reserved', models.DateField()),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
