# Generated by Django 3.0 on 2020-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrescoBasilico', '0010_auto_20200207_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'two guests table no 1'), (2, 'two guests table no 2'), (3, 'two guests table no 3'), (4, 'two guests table no 4'), (5, 'two guests table no 5'), (6, 'two guests table no 6'), (7, 'four guests table no 7'), (8, 'four guests table no 8'), (9, 'four guests table no 9'), (10, 'four guests table no 10'), (11, 'four guests table no 11'), (12, 'eight guests table no 12'), (13, 'three guests table no 13')], default=1),
        ),
    ]
